### ISSUE TITLE
unable to install grunt-net

### ISSUE THREAD

**Issue by krishanth30** [shama/grunt-net#2]
npm install grunt-net
npm WARN package.json grunt@0.4.5 No license field.
\

> weak@0.2.2 install /home/rkrishanth/node_modules/grunt/node_modules/grunt-net/node_modules/dnode/node_modules/weak
> node-gyp rebuild

make: Entering directory `/home/rkrishanth/node_modules/grunt/node_modules/grunt-net/node_modules/dnode/node_modules/weak/build'
  CXX(target) Release/obj.target/weakref/src/weakref.o
In file included from ../src/weakref.cc:18:
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:336: error: expected unqualified-id before âusingâ
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h: In constructor âv8::MaybeLocal<T>::MaybeLocal()â:
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:353: error: ânullptrâ was not declared in this scope
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h: In member function âbool v8::MaybeLocal<T>::IsEmpty() constâ:
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:360: error: ânullptrâ was not declared in this scope
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h: In member function âbool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) constâ:
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:364: error: ânullptrâ was not declared in this scope
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h: In member function âbool v8::WeakCallbackInfo<T>::IsFirstPass() constâ:
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:430: error: ânullptrâ was not declared in this scope
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h: At global scope:
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:469: error: expected unqualified-id before âusingâ
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h: In constructor âv8::Global<T>::Global()â:
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:790: error: ânullptrâ was not declared in this scope
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h: In constructor âv8::Global<T>::Global(v8::Global<T>&&)â:
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:815: error: ânullptrâ was not declared in this scope
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h: In member function âv8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)â:
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:827: error: ânullptrâ was not declared in this scope
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h: At global scope:
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:852: error: expected unqualified-id before âusingâ
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:1089: error: ânullptrâ was not declared in this scope
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:1095: error: ânullptrâ was not declared in this scope
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h: In member function âv8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) constâ:
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:3205: error: ânullptrâ was not declared in this scope
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h: In member function âv8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()â:
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:7164: error: ânullptrâ was not declared in this scope
../src/weakref.cc: At global scope:
../src/weakref.cc:38: error: âHandleâ was not declared in this scope
../src/weakref.cc:38: error: expected primary-expression before â>â token
../src/weakref.cc:38: error: âproxyâ was not declared in this scope
../src/weakref.cc:38: error: expected â,â or â;â before â{â token
../src/weakref.cc:50: error: expected constructor, destructor, or type conversion before â<â token
../src/weakref.cc:61: error: expected constructor, destructor, or type conversion before â<â token
../src/weakref.cc:80: error: expected constructor, destructor, or type conversion before â<â token
../src/weakref.cc:87: error: expected constructor, destructor, or type conversion before â<â token
../src/weakref.cc:96: error: expected constructor, destructor, or type conversion before â<â token
../src/weakref.cc:102: error: expected constructor, destructor, or type conversion before â<â token
../src/weakref.cc:109: error: expected constructor, destructor, or type conversion before â<â token
../src/weakref.cc:116: error: expected constructor, destructor, or type conversion before â<â token
../src/weakref.cc:125: error: expected constructor, destructor, or type conversion before â<â token
../src/weakref.cc:131: error: expected constructor, destructor, or type conversion before â<â token
../src/weakref.cc:138: error: expected constructor, destructor, or type conversion before â<â token
../src/weakref.cc:144: error: variable or field âAddCallbackâ declared void
../src/weakref.cc:144: error: âHandleâ was not declared in this scope
../src/weakref.cc:144: error: expected primary-expression before â>â token
../src/weakref.cc:144: error: âproxyâ was not declared in this scope
../src/weakref.cc:144: error: âHandleâ was not declared in this scope
../src/weakref.cc:144: error: expected primary-expression before â>â token
../src/weakref.cc:144: error: âcallbackâ was not declared in this scope
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h: In function âvoid<unnamed>::TargetCallback(v8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >, void*)â:
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:885: error: âv8::HandleScope::HandleScope()â is protected
../src/weakref.cc:151: error: within this context
../src/weakref.cc:158: error: base operand of â->â has non-pointer type âv8::Persistent<v8::Array, v8::NonCopyablePersistentTraits<v8::Array> >â
../src/weakref.cc:159: error: âHandleâ was not declared in this scope
../src/weakref.cc:159: error: expected primary-expression before â>â token
../src/weakref.cc:159: error: âargvâ was not declared in this scope
../src/weakref.cc:163: error: expected primary-expression before â>â token
../src/weakref.cc:163: error: âcbâ was not declared in this scope
../src/weakref.cc:163: error: expected primary-expression before â>â token
../src/weakref.cc:163: error: â::Castâ has not been declared
../src/weakref.cc:164: error: base operand of â->â has non-pointer type âv8::Persistent<v8::Array, v8::NonCopyablePersistentTraits<v8::Array> >â
../src/weakref.cc:164: error: no matching function for call to âv8::Integer::New(uint32_t&)â
/home/rkrishanth/.node-gyp/4.2.1/include/node/v8.h:2499: note: candidates are: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
../src/weakref.cc:168: error: base operand of â->â has non-pointer type âv8::Persistent<v8::Value, v8::NonCopyablePersistentTraits<v8::Value> >â
../src/weakref.cc:176: error: base operand of â->â has non-pointer type âv8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >â
../src/weakref.cc:180: error: âclass v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >â has no member named âDisposeâ
../src/weakref.cc:181: error: âclass v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >â has no member named âClearâ
../src/weakref.cc:182: error: âclass v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >â has no member named âDisposeâ
../src/weakref.cc:183: error: âclass v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >â has no member named âClearâ
../src/weakref.cc:184: error: âclass v8::Persistent<v8::Array, v8::NonCopyablePersistentTraits<v8::Array> >â has no member named âDisposeâ
../src/weakref.cc:185: error: âclass v8::Persistent<v8::Array, v8::NonCopyablePersistentTraits<v8::Array> >â has no member named âClearâ
../src/weakref.cc: At global scope:
../src/weakref.cc:190: error: expected constructor, destructor, or type conversion before â<â token
../src/weakref.cc:340: error: expected â}â at end of input
../src/weakref.cc:38: warning: â<unnamed>::IsDeadâ defined but not used
make: *** [Release/obj.target/weakref/src/weakref.o] Error 1
make: Leaving directory`/home/rkrishanth/node_modules/grunt/node_modules/grunt-net/node_modules/dnode/node_modules/weak/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/rkrishanth/node-v4.2.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.8.13-98.2.1.el6uek.x86_64
gyp ERR! command "/home/rkrishanth/node-v4.2.1-linux-x64/bin/node" "/home/rkrishanth/node-v4.2.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rkrishanth/node_modules/grunt/node_modules/grunt-net/node_modules/dnode/node_modules/weak
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 3.8.13-98.2.1.el6uek.x86_64
npm ERR! argv "/home/rkrishanth/node-v4.2.1-linux-x64/bin/node" "/home/rkrishanth/node-v4.2.1-linux-x64/bin/npm" "install" "grunt-net"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! weak@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the weak@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the weak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls weak
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rkrishanth/node_modules/grunt/npm-debug.log

I tried to update node to 4.2.1 and npm to 2.14.7
I also tried updating python to 2.7.11 and npm install -g node-gyp still no luck.
Do you have any idea why this is failing?

**Comment by shama** [comment]
Looks like the dependencies needed an update to work with later versions of Node. Give `grunt-net@1.0.0` a try. Thanks!

**Comment by krishanth30** [comment]
Thanks. That worked!
